FONT_FILENAME = "font_score.ttf"
FONT_SCORE_SIZE = 380
CJPC_FILENAME = "cjpc.png"
POR_FILENAME = "por.png"
BACK_FILENAME = "hasil-pertandingan.jpg"
CABANG = "MEN'S BASKETBALL"
FONT_POINTS_INT_SIZE = 450
FONT_TEAM_STR_SIZE = 135
FONT_CABANG_STR_SIZE = 196
FONT_TITLE_STR_SIZE = 161

